### ISSUE TITLE
Accessing some collections not working since upgrade to 9.14.1

### ISSUE THREAD

**Issue by jbauzone** [ForestAdmin/forest-rails#736]
Hi there, I have a strange issue with upgrade to version 9.14.1.

## Actual behavior
When accessing some collections but not all, and I don't know what the not working ones have in common, in my case, it about some unreleated collections, I meet the error in console : `UnknownClientRecordAgentError: Expected id to be a string or number, received null`

<img width="1416" alt="Image" src="https://github.com/user-attachments/assets/3d50311f-b4e8-4a44-902d-98dc9e7bdd94" />

## Expected behavior

I can access my collection.

**Comment by jbauzone** [comment]
hi @matthv , sure, I don't have this problem using version 9.13.0. I also tried on 9.14.0 but I have another problem on all collection this time and can't access no collection at all :

One example :
```
[2025-06-02 09:07:30 +0000] Forest 🌳🌳🌳  Records Index error: undefined method `organisation_id' for #<Organisation id: 248, name: "Organisation Alexis".....
```

On another collection if this can help :

```
Forest 🌳🌳🌳  Records Index error: undefined method `category_id' for #<BenefitEvent id: 15, name: "Subvention".....
```

**Comment by matthv** [comment]
Thanks a lot for the quick reply! That’s super helpful 🙏
Indeed, I’d recommend avoiding version 9.14.0 for now, as it introduced another issue currently under investigation.
I’ll keep you posted as soon as I have more info.

**Comment by matthv** [comment]
Hello @jbauzone, to help us investigate the issue further, could you please share the logs from your rails app while using version 9.14.1?

**Comment by jbauzone** [comment]
Getting same issue on 9.14.2 if it can help. :)

**Comment by jbauzone** [comment]
Hi,

I could generate a response which I can share publicly.

Here are :
- the payload response from `/forest/Order` : [orders response.json](https://github.com/user-attachments/files/20819013/orders.response.json)
- our order table data [orders_structure.csv](https://github.com/user-attachments/files/20819030/orders_structure.csv)

There is no special customization on this collection, we only have a smart action but very simple : 
 ` action 'Cancel Order', type: 'single'`
